import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import type { OpportunityOutcome, Placement, PlacementPartner, ShareBasis } from "../packages/specification/types.js";

export interface LedgerRow { site_id:string; slot_id:string; partner_id:string; opportunities_assigned:number; confirmed_fills:number; no_fills:number; failures:number; last_selected_at?:string; }
export interface OpportunityCycle { cycle_id:string; site_id:string; slot_id:string; selected_partner_id:string; final_partner_id?:string; final_unit_id?:string; outcome:string; created_at:string; completed_at?:string; }
export interface SelectionReason { selected_partner:string; reason:string; target_share:number; actual_fill_share:number; share_debt:number; }
const allowed = /^[a-zA-Z0-9._-]+$/;
function assertSafe(id:string,name:string){ if(!allowed.test(id)) throw new Error(`invalid ${name}`); }
export class ShareLedger {
  dbPath:string;
  constructor(dataDir:string){ this.dbPath=path.join(dataDir,"share-ledger.sqlite"); mkdirSync(path.dirname(this.dbPath),{recursive:true}); this.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS partner_slot_ledger (site_id TEXT NOT NULL, slot_id TEXT NOT NULL, partner_id TEXT NOT NULL, opportunities_assigned INTEGER NOT NULL DEFAULT 0, confirmed_fills INTEGER NOT NULL DEFAULT 0, no_fills INTEGER NOT NULL DEFAULT 0, failures INTEGER NOT NULL DEFAULT 0, last_selected_at TEXT, PRIMARY KEY (site_id, slot_id, partner_id)); CREATE TABLE IF NOT EXISTS opportunity_cycles (cycle_id TEXT PRIMARY KEY, site_id TEXT NOT NULL, slot_id TEXT NOT NULL, selected_partner_id TEXT NOT NULL, final_partner_id TEXT, final_unit_id TEXT, outcome TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT);`); }
  exec(sql:string){ return execFileSync("sqlite3",[this.dbPath,sql],{encoding:"utf8"}); }
  query(sql:string){ return execFileSync("sqlite3",["-json",this.dbPath,sql],{encoding:"utf8"}); }
  rows(site:string,slot:string):LedgerRow[]{ assertSafe(site,"site id"); assertSafe(slot,"slot id"); const out=this.query(`SELECT * FROM partner_slot_ledger WHERE site_id=${q(site)} AND slot_id=${q(slot)} ORDER BY partner_id;`); return out.trim()?JSON.parse(out):[]; }
  cycles(site?:string,limit=50):OpportunityCycle[]{ const where=site?`WHERE site_id=${q(site)}`:""; const out=this.query(`SELECT * FROM opportunity_cycles ${where} ORDER BY created_at DESC LIMIT ${Number(limit)||50};`); return out.trim()?JSON.parse(out):[]; }
  select(site:string, placement:Placement, debug=false){ assertSafe(site,"site id"); assertSafe(placement.id,"slot id"); const partners=normalizePartners(placement.partners??migratePartners(placement)); const existing=this.rows(site,placement.id); const selected=selectPartner(partners, existing, placement.share_basis??"confirmed-fills"); const now=new Date().toISOString(); const cycle=randomUUID(); this.exec(`BEGIN IMMEDIATE; INSERT INTO partner_slot_ledger(site_id,slot_id,partner_id,opportunities_assigned,last_selected_at) VALUES(${q(site)},${q(placement.id)},${q(selected.partner.partner_id)},1,${q(now)}) ON CONFLICT(site_id,slot_id,partner_id) DO UPDATE SET opportunities_assigned=opportunities_assigned+1,last_selected_at=${q(now)}; INSERT INTO opportunity_cycles(cycle_id,site_id,slot_id,selected_partner_id,outcome,created_at) VALUES(${q(cycle)},${q(site)},${q(placement.id)},${q(selected.partner.partner_id)},'selected',${q(now)}); COMMIT;`);
    return {cycle_id:cycle, site, slot:placement.id, partner:selected.partner.partner_id, share_policy:placement.share_policy??"open-yield", lane:selected.partner.lane, debug:debug?selected.reason:undefined}; }
  outcome(site:string, slot:string, body:{cycle_id:string; selected_partner?:string; final_partner?:string; unit?:string; outcome:OpportunityOutcome}){ assertSafe(site,"site id"); assertSafe(slot,"slot id"); assertSafe(body.cycle_id,"cycle id"); const current=this.query(`SELECT * FROM opportunity_cycles WHERE cycle_id=${q(body.cycle_id)};`); const rows=current.trim()?JSON.parse(current):[]; if(!rows.length) throw new Error("unknown opportunity cycle"); if(rows[0].completed_at) return {ok:true,idempotent:true}; const finalPartner=body.final_partner||""; if(finalPartner) assertSafe(finalPartner,"partner id"); const now=new Date().toISOString(); let inc=""; if(body.outcome==="filled"||body.outcome==="recovery-fill") inc=`confirmed_fills=confirmed_fills+1`; else if(body.outcome==="no-fill"||body.outcome==="neutral-fallback"||body.outcome==="collapsed") inc=`no_fills=no_fills+1`; else inc=`failures=failures+1`;
    const credit=(body.outcome==="filled"||body.outcome==="recovery-fill")&&finalPartner?`INSERT INTO partner_slot_ledger(site_id,slot_id,partner_id) VALUES(${q(site)},${q(slot)},${q(finalPartner)}) ON CONFLICT DO NOTHING; UPDATE partner_slot_ledger SET ${inc} WHERE site_id=${q(site)} AND slot_id=${q(slot)} AND partner_id=${q(finalPartner)};`:"";
    this.exec(`BEGIN IMMEDIATE; UPDATE opportunity_cycles SET final_partner_id=${q(finalPartner||"")}, final_unit_id=${q(body.unit||"")}, outcome=${q(body.outcome)}, completed_at=${q(now)} WHERE cycle_id=${q(body.cycle_id)} AND completed_at IS NULL; ${credit} COMMIT;`); return {ok:true,idempotent:false}; }
}
function q(s:string){return `'${String(s).replaceAll("'","''")}'`;}
export function normalizePartners(partners:PlacementPartner[]){ if(partners.some(p=>p.share_target<0)) throw new Error("invalid Share Target: negative shares are not allowed"); const total=partners.reduce((s,p)=>s+p.share_target,0); if(total<=0) throw new Error("invalid Share Target: every Share Target is zero"); return partners.map(p=>({...p, normalized_share:p.share_target/total})); }
function migratePartners(p:Placement):PlacementPartner[]{ return [{partner_id:"legacy",partner_name:"Legacy",share_target:100,lane:p.candidates??[]}]; }
export function selectPartner(partners:ReturnType<typeof normalizePartners>, ledger:LedgerRow[], basis:ShareBasis){ const by=new Map(ledger.map(r=>[r.partner_id,r])); const totalFills=ledger.reduce((s,r)=>s+r.confirmed_fills,0); const totalOpp=ledger.reduce((s,r)=>s+r.opportunities_assigned,0); const scored=partners.map((p,i)=>{ const r=by.get(p.partner_id); const actualFill=totalFills?((r?.confirmed_fills??0)/totalFills):0; const actualOpp=totalOpp?((r?.opportunities_assigned??0)/totalOpp):0; let debt=p.normalized_share-(basis==="weighted-opportunities"?actualOpp:actualFill); if(basis==="round-robin") debt=-(r?.opportunities_assigned??0); return {partner:p, index:i, r, debt, reason:basis==="confirmed-fills"&&totalFills?"largest-share-debt":basis}; }); scored.sort((a,b)=> b.debt-a.debt || (a.r?.confirmed_fills??0)-(b.r?.confirmed_fills??0) || String(a.r?.last_selected_at??"").localeCompare(String(b.r?.last_selected_at??"")) || a.partner.partner_id.localeCompare(b.partner.partner_id)); const s=scored[0]; return {partner:s.partner, reason:{selected_partner:s.partner.partner_id,reason:s.reason,target_share:s.partner.normalized_share,actual_fill_share:totalFills?((s.r?.confirmed_fills??0)/totalFills):0,share_debt:s.debt} as SelectionReason}; }
